// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * Greet returns a greeting for the given name
 * @param {string} name
 * @returns {Promise<string> & { cancel(): void }}
 */
export function Greet(name) {
    let $resultPromise = /** @type {any} */($Call.ByID(1411160069, name));
    return $resultPromise;
}

/**
 * @param {string} ips
 * @returns {Promise<string> & { cancel(): void }}
 */
export function PingIP(ips) {
    let $resultPromise = /** @type {any} */($Call.ByID(2894228405, ips));
    return $resultPromise;
}

/**
 * @param {string} url
 * @returns {Promise<string> & { cancel(): void }}
 */
export function RequestForFront(url) {
    let $resultPromise = /** @type {any} */($Call.ByID(2244485623, url));
    return $resultPromise;
}
